// packages/frontend/src/graph/legend/Legend.tsx
import _ from 'lodash';
import {
  isSameMonth,
  format as formatDate,
  addDays,
  isSameYear,
} from 'date-fns';
import './legend.styl';

function formatInterval(startOfPeriod, interval: number) {
  const endOfPeriod = addDays(startOfPeriod, interval - 1);
  if (isSameMonth(startOfPeriod, endOfPeriod)) {
    return `${formatDate(startOfPeriod, 'MMMM Do')} - ${formatDate(
      endOfPeriod,
      'Do',
    )}, ${formatDate(startOfPeriod, 'YYYY')}`;
  } else if (isSameYear(startOfPeriod, endOfPeriod)) {
    return `${formatDate(startOfPeriod, 'MMMM Do')} - ${formatDate(
      endOfPeriod,
      'MMMM Do',
    )}, ${formatDate(startOfPeriod, 'YYYY')}`;
  }
  return `${formatDate(startOfPeriod, 'MMMM Do, YYYY')} - ${formatDate(
    endOfPeriod,
    'MMMM Do, YYYY',
  )}`;
}

export const Legend = ({
  modules,
  onPackageFocus,
  onPackageBlur,
  onLegendBlur,
  onLegendFocus,
  onRemovePackage,
  interval,
  date,
}) => {
  const sortedModules = _.orderBy(modules, module => module.entries, ['desc']);
  return (
    <div className="legend">
      <div
        className="date"
        style={{ display: interval > 1 ? 'block' : 'none' }}
      >
        {formatInterval(date, interval)}
      </div>
      <div
        className="date"
        style={{ display: interval <= 1 ? 'block' : 'none' }}
      >
        {formatDate(date, 'dddd MMMM Do, YYYY')}
      </div>
      <table className="modules">
        <tbody onMouseOver={onLegendFocus} onMouseLeave={onLegendBlur}>
          {sortedModules.map(module => (
            <tr
              className="module"
              key={module.name}
              style={{ color: module.color }}
              onMouseOver={() => onPackageFocus(module.name)}
              onMouseLeave={() => onPackageBlur(module.name)}
            >
              <td className="actions">
                <button
                  className="remove-entry-button"
                  onClick={() => onRemovePackage(module.name)}
                  title={`remove '${module.name}' from comparison`}
                >
                  <div
                    className="nub"
                    style={{
                      // @ts-expect-error Type '{ '--module-color': any; }' is not assignable to type 'Properties<string | number, string & {}>'.
                      '--module-color': module.color,
                    }}
                  ></div>
                </button>
              </td>
              <td className="name-wrapper">
                <div className="name">{module.name}</div>
              </td>
              <td className="downloads" style={{ minWidth: '4.5em' }}>
                {module.downloads.toLocaleString()}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};

// packages/frontend/src/graph/legend/legend.vue
<template>
    <div
  class="legend"
>
  <div class="date" v-if="interval > 1">
    {{formatInterval(date)}}
  </div>
  <div class="date" v-else>
    {{date | formatDate('dddd MMMM Do, YYYY')}}
  </div>
  <table class="modules">
    <tbody
      @mouseover="handleMouseEnterLegend()"
      @mouseleave="handleMouseLeaveLegend()"
    >
      <tr
        class="module"
        v-for="module in sortedModules"
        track-by="name"
        :style="{color: module.color}"
        @mouseover="handleMouseEnterPackage(module.name)"
        @mouseleave="handleMouseLeavePackage(module.name)"
      >
        <td class="actions">
          <button class="remove-entry-button" @click="removePackage(module.name)" :title="`remove '${module.name}' from comparison`">
            <div class="nub" :style="{ '--module-color': module.color }"></div>
          </button>
        </td>
        <td class="name-wrapper">
          <div class="name">
            {{module.name}}
          </div>
        </td>
        <td class="downloads" style="min-width: 4.5em;">
          {{module.downloads.toLocaleString()}}
        </td>
      </tr>
    </tbody>
  </table>
</div>
</template>

<script>
import _ from 'lodash';
import { removePackage } from '../../packages/packages.js';
import {
    isSameMonth,
    format as formatDate,
    addDays,
    isSameYear,
} from 'date-fns';

export default {
    props: {
        modules: Array,
        date: Date,
        interval: Number,
    },
    computed: {
        sortedModules() {
            return _.orderBy(this.modules, module => module.entries, ['desc']);
        },
    },
    // template: require('./legend.html'),
    methods: {
        removePackage(packageName) {
            ga('send', 'event', 'legend', 'remove', packageName);
            removePackage(packageName);
            this.$emit('legend-blur');
        },
        handleMouseEnterLegend() {
            this.$emit('legend-focus');
        },
        handleMouseLeaveLegend() {
            this.$emit('legend-blur');
        },
        handleMouseEnterPackage(packageName) {
            this.$emit('package-focus', packageName);
        },
        handleMouseLeavePackage(packageName) {
            this.$emit('package-blur', packageName);
        },
        formatInterval(startOfPeriod) {
            const endOfPeriod = addDays(startOfPeriod, this.interval - 1);
            if (isSameMonth(startOfPeriod, endOfPeriod)) {
                return `${formatDate(startOfPeriod, 'MMMM Do')} - ${formatDate(
                    endOfPeriod,
                    'Do',
                )}, ${formatDate(startOfPeriod, 'YYYY')}`;
            } else if (isSameYear(startOfPeriod, endOfPeriod)) {
                return `${formatDate(startOfPeriod, 'MMMM Do')} - ${formatDate(
                    endOfPeriod,
                    'MMMM Do',
                )}, ${formatDate(startOfPeriod, 'YYYY')}`;
            }
            return `${formatDate(startOfPeriod, 'MMMM Do, YYYY')} - ${formatDate(
                endOfPeriod,
                'MMMM Do, YYYY',
            )}`;
        },
    },
}
</script>

<style lang="styl" src="./legend.styl">

</style>
